name: Auto Pack ZIP

on:
  push:
    branches:
      - main     # 如果提示找不到分支，改成 master

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip project
        run: |
          zip -r miniprogram.zip . \
            -x ".git/*" ".github/*" "*.md"

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: miniprogram
          path: miniprogram.zip
